@startuml
left to right direction

actor 疑似患者
疑似患者<|--确诊病例
actor 医生
疑似患者-->(检查)
确诊病例-->(检查)

rectangle  诊断{
  (检查) ..> (体温监测) : include
  (体温监测)-->(核酸检测)
  (检查) ..> (核酸检测) :include
  (核酸检测)-->(PCR检查)
  (检查) ..>(PCR检查):include

}
检查-->(排除风险)
检查-->(信息系统)
(信息系统)-->(分析系统)
rectangle 确诊病例信息管理系统{
(信息系统)..>(信息删除):include
(信息系统)..>(信息查询):include
(信息系统)..>(信息录入):include
(信息系统)..>(信息修改):include
}
rectangle 数据分析{
    医生-->(分析系统)
    (分析系统)-->(检查)
    (数据建模)-->(可视化)
    (分析系统).>(数据建模):include
    (分析系统).>(可视化):include
    (分析系统).>(分析):include
    (可视化)-->(分析)
}

@enduml
